version: '3'

services:
  db:
    platform: linux/x86_64
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - ./db:/var/lib/mysql
    env_file:
      - .dev.env
  api:
    build: 
      context: .
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./api:/app
    working_dir: /app
    command: sh -c "/wait &&
      python manage.py migrate &&
      python manage.py runserver 0.0.0.0:8000"
    env_file:
      - .dev.env
    depends_on:
      - db
    links:
      - db
    environment:
      WAIT_HOSTS: db:3306
  web:
    image: node:12-alpine
    volumes:
      - ./web:/app
    working_dir: /app
    ports:
      - 3000:3000
    command: npm start
    env_file:
      - .dev.env
    depends_on:
      - api
    links:
      - api
