# Generated by Django 3.2.6 on 2021-09-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0003_auto_20210901_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='accountName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='clientName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='iCOperation',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
