# Generated by Django 3.2.6 on 2021-09-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0004_auto_20210901_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
