# Generated by Django 3.2.6 on 2021-09-03 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nexus', '0005_auto_20210903_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='movements',
            name='state',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='team',
            name='state',
            field=models.BooleanField(default=True),
        ),
    ]
